# Generated by Django 5.0 on 2024-01-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_money_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Money',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='event_name',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='friend_email',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='friend_name',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='your_email',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='your_name',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
