# Generated by Django 5.0 on 2024-01-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_delete_money_remove_user_email_remove_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='event_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='friend_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='friend_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='your_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='your_name',
            field=models.CharField(max_length=100),
        ),
    ]
